title: My Jekyll Blog
description: A blog about my journey and experiences.
author:
  name: Your Name
  email: your.email@example.com
url: https://yourusername.github.io/my-jekyll-blog
baseurl: ""
paginate: 5
markdown: kramdown
theme: minima